#!/bin/bash

{
	while read repo;
do
	curl 'https://registry.hub.docker.com/v2/repositories/eventdrivenrobotics/yarp/tags'
	tags=`wget -q https://registry.hub.docker.com/v1/repositories/$repo/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}'`

	read -ra tags_array <<< "$tags"

	while read -r tag; do
		echo "docker build --build-arg from=$repo:$tag -t $repo:${tag}_opengl ."
	done <<< "$tags"
done
} < repos.txt
