#!/bin/bash

{
	while read repo;
do
	tags=`wget -q https://registry.hub.docker.com/v1/repositories/$repo/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}'`

	read -ra tags_array <<< "$tags"

	while read -r tag; do
		docker push $repo:${tag}_opengl
	done <<< "$tags"
done
} < repos.txt
